config/routes.rb
SampleApp::Application.routes.draw do

  get "sessions/new"

  get "pages/home"
  get "pages/contact"
  get "pages/about"
  get "pages/help"
  
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :sessions, :only => [:new, :create, :destroy]
  resources :microposts, :only => [:create, :destroy]
  resources :relationships, :only => [:create, :destroy]
  
  
  match '/contact', :to => 'pages#contact'
  match '/about', :to  => 'pages#about'
  match '/help', :to => 'pages#help'
  match '/signup', :to => 'users#new'
  match '/signin', :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'
  root :to => 'pages#home'

end

app/views/layouts/_footer.html.haml
%footer
  %nav{:class => "round"}
    %ul
      %li= link_to "About", about_path
      %li= link_to "Contact", contact_path
      %li <a href="http://news.railtutorials.org/">News</a>
      %li <a href="http://www.railstutorial.org/">Rails Tutorial</a>

app/views/layouts/_header.html.haml
%header
  = link_to logo, root_path
  %nav{ :class => "round"}
    %ul
      %li= link_to "Home", root_path
      - if signed_in?
        %li= link_to "Users", users_path
        %li= link_to "Profile", current_user
        %li= link_to "Settings", edit_user_path(current_user)
      %li= link_to "Help", help_path
      - if signed_in?
        %li= link_to "Sign out", signout_path, :method => :delete
      - else
        %li= link_to "Sign in", signin_path
    

app/views/layouts/_stylesheets.html.haml
<!-- [if lt IE 9]>
<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"><script>
<![endif]-->
= stylesheet_link_tag 'blueprint/screen', :media => 'screen'
= stylesheet_link_tag 'blueprint/print',  :media => 'print'
<!--[if lt IE 8]><%= stylesheet_link_tag 'blueprint/ie' %><![endif]-->
= stylesheet_link_tag 'custom.css', :media => 'screen'

app/views/layouts/application.html.haml
!!! html
%html
  %head
    %title= title
    = csrf_meta_tag
    = render "layouts/stylesheets"
    = javascript_include_tag :defaults
  %body
    %div{:class => "container"}
      = render "layouts/header"
      %section{ :class => "round"}
        - flash.each do |key,value|
          %div{:class => "flash #{key}"} #{value}
        = yield
      = render "layouts/footer"
      = debug(params) if Rails.env.development?